FROM python:3.12-slim

COPY dashboard/db_requirements.txt .

RUN pip install -r db_requirements.txt

COPY queries.py .

COPY graphs.py .

COPY dashboard.py .

# listen on port 8501 for Streamlit
EXPOSE 8501

# Define the command that runs when we type `docker run container`
CMD ["streamlit", "run", "dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]